Code by Manoj Mangam

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

In [2]:
# create a simulated dataset without multicollinearity
np.random.seed(123)
n = 100
#Features  
x1 = np.random.normal(size=n)
#True Population Line
y = 1 + 2*x1 + np.random.normal(size=n, scale=0.5) 

data = pd.DataFrame({'x1': x1,'y': y})

In [3]:
# fit a linear regression model using statsmodels
X = sm.add_constant(data['x1'])
model = sm.OLS(data['y'], X).fit()

# print the summary statistics of the model
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.956
Model:                            OLS   Adj. R-squared:                  0.955
Method:                 Least Squares   F-statistic:                     2104.
Date:                Tue, 18 Apr 2023   Prob (F-statistic):           4.83e-68
Time:                        12:42:09   Log-Likelihood:                -69.520
No. Observations:                 100   AIC:                             143.0
Df Residuals:                      98   BIC:                             148.3
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9905      0.049     20.213      0.000       0.893       1.088
x1             1.9917      0.043     45.873      0.000       1.906       2.078
==============================================================================
Omnibus:                        5.027   Durbin-Watson:                   1.860
Prob(Omnibus):                  0.081   Jarque-Bera (JB):                5.131
Skew:                          -0.308   Prob(JB):                       0.0769
Kurtosis:                       3.924   Cond. No.                         1.13
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [4]:
#check the (X'X)^-1 matrix, an indication of coeff. variances
X = np.vstack(x1)
X_t= np.transpose(X)
XtX = np.dot(X_t, X)
np.linalg.inv(XtX)

array([[0.00785138]])

Mild

In [5]:
# create a simulated dataset with milder multicollinearity
np.random.seed(123)
n = 100
#Features
x1 = np.random.normal(size=n)
x2 = 0.5*x1 + np.random.normal(size=n, scale=0.1)
#True Population Line
y = 1 + 2*x1 + np.random.normal(size=n, scale=0.5)

data = pd.DataFrame({'x1': x1, 'x2': x2, 'y': y})

In [6]:
# fit a linear regression model using statsmodels
X = sm.add_constant(data[['x1', 'x2']])
model = sm.OLS(data['y'], X).fit()

# print the summary statistics of the model
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.955
Model:                            OLS   Adj. R-squared:                  0.954
Method:                 Least Squares   F-statistic:                     1028.
Date:                Tue, 18 Apr 2023   Prob (F-statistic):           5.02e-66
Time:                        12:42:09   Log-Likelihood:                -69.269
No. Observations:                 100   AIC:                             144.5
Df Residuals:                      97   BIC:                             152.4
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9534      0.049     19.402      0.000       0.856       1.051
x1             1.9175      0.256      7.488      0.000       1.409       2.426
x2             0.1136      0.506      0.224      0.823      -0.892       1.119
==============================================================================
Omnibus:                        1.671   Durbin-Watson:                   1.841
Prob(Omnibus):                  0.434   Jarque-Bera (JB):                1.328
Skew:                           0.280   Prob(JB):                        0.515
Kurtosis:                       3.079   Cond. No.                         14.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [7]:
#check the (X'X)^-1 matrix, an indication of coeff. variances

X = np.concatenate((np.vstack(x1),np.vstack(x2)),axis=1)
X_t= np.transpose(X)
XtX = np.dot(X_t, X)
np.linalg.inv(XtX)

array([[ 0.27171788, -0.52953328],
       [-0.52953328,  1.06267942]])

In [8]:
#find the VIF of each variable to get a sense of amount of multicollenarity
#Rule of thumb VIF > 5 indicates a problematic amount of multicollinearity
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_data = pd.DataFrame()
data.drop(columns='y', inplace=True)
vif_data["feature"] = data.columns
  
# calculating VIF for each feature
vif_data["VIF"] = [variance_inflation_factor(data.values, i)
                          for i in range(len(data.columns))]
  
vif_data

  feature        VIF
0      x1  34.607659
1      x2  34.607659

Exact

In [9]:
# create a simulated dataset with exact multicollinearity
np.random.seed(123)
n = 100
#Features 
x1 = np.random.normal(size=n)
x2 = 0.5*x1 
#True Population Line
y = 1 + 2*x1 + np.random.normal(size=n, scale=0.5)

data = pd.DataFrame({'x1': x1, 'x2': x2, 'y': y})

In [10]:
# fit a linear regression model using statsmodels
X = sm.add_constant(data[['x1', 'x2']])
model = sm.OLS(data['y'], X).fit()

# print the summary statistics of the model
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.956
Model:                            OLS   Adj. R-squared:                  0.955
Method:                 Least Squares   F-statistic:                     2104.
Date:                Tue, 18 Apr 2023   Prob (F-statistic):           4.83e-68
Time:                        12:42:09   Log-Likelihood:                -69.520
No. Observations:                 100   AIC:                             143.0
Df Residuals:                      98   BIC:                             148.3
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9905      0.049     20.213      0.000       0.893       1.088
x1             1.5934      0.035     45.873      0.000       1.524       1.662
x2             0.7967      0.017     45.873      0.000       0.762       0.831
==============================================================================
Omnibus:                        5.027   Durbin-Watson:                   1.860
Prob(Omnibus):                  0.081   Jarque-Bera (JB):                5.131
Skew:                          -0.308   Prob(JB):                       0.0769
Kurtosis:                       3.924   Cond. No.                     1.33e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.07e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [11]:
#find the VIF of each variable to get a sense of amount of multicollenarity
#Rule of thumb VIF > 5 indicates a problematic amount of multicollinearity

vif_data = pd.DataFrame()
data.drop(columns='y', inplace=True)
vif_data["feature"] = data.columns
  
# calculating VIF for each feature
vif_data["VIF"] = [variance_inflation_factor(data.values, i)
                          for i in range(len(data.columns))]
  
vif_data

/Users/chenhajaj/miniforge3/lib/python3.9/site-packages/statsmodels/stats/outliers_influence.py:195: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

  feature  VIF
0      x1  inf
1      x2  inf